### ISSUE TITLE
Missing Dependencies

### ISSUE THREAD

**Issue by knksmith57** [electrode-io/generator-electrode#33]
Heya Team,

First off, big hat tip on this _entire_ project! Docs are excellent. Site is beautiful. Blog post is exciting. Docker support + examples are a big plus.

While following the [Get Started](http://www.electrode.io/docs/get_started.html) guide and making use of this generator, I ran into a few missing dependency issues.

TL;DR here are the additional packages I needed to install to get up and running:
* babel-preset-es2015
* react-router
* react-resolver
* babel-runtime
* inert (this error happened after getting past the initial webpack build issues and once I tried to hit the running server)

I'll stop here and post a follow-up comment w/ repro details.

Cheers!

**Comment by knksmith57** [comment]
OK, my reproduce steps + commands

```
❯ npm i -g yo gulp generator-electrode
```
nothing exciting here. [raw output log](https://gist.github.com/knksmith57/b3767d64f2f75b5dbb0154bf965bbd70)

```
❯ yo electrode

     _-----_     ╭──────────────────────────╮
    |       |    │      Welcome to the      │
    |--(o)--|    │ phenomenal Electrode App │
   `---------´   │        generator!        │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

? Application Name example-electrode-app
? Description
? Project homepage url
? Author's Name Kyle Smith
? Author's Email kbsmith@rmn.com
? Author's Homepage
? Package keywords (comma to split)
? GitHub username or organization
? Which license do you want to use? MIT
   create package.json
   create README.md
   create .editorconfig
   create .gitattributes
   create .gitignore
   create .babelrc
   create gulpfile.js
   create client/app.jsx
   create client/components/home.jsx
   create client/routes.jsx
   create client/styles/base.css
   create config/default.json
   create config/development.json
   create config/production.js
   create config/production.json
   create server/index.js
   create test/client/components/home.spec.jsx
   create .travis.yml
   create LICENSE
   create server/plugins/webapp/index.html
   create server/plugins/webapp/index.js
   create server/views/index-view.jsx


I'm all done. Running npm install && bower install for you to install the required dependencies. If this fails, try running the command yourself.
```
nothing exciting here. [raw output log](https://gist.github.com/knksmith57/b2e0788d4e3818201c77a560f4f29e39)

add custom ignores:
```
❯ gibo node osx >> .gitignore
```
here's what [`.gitignore`](https://gist.github.com/knksmith57/83558ff30102e9b9c1c0796da69f5c2a) looks like after. (later realized this probably wasn't even required lolol).

OK now first run of `gulp dev`:
```
❯ gulp dev
[16:27:07] Using gulpfile ~/work/scratch/example-electrode-app/gulpfile.js
[16:27:07] Starting 'dev'...
[16:27:07] Starting '.webpack-dev'...
[16:27:07] Finished '.webpack-dev' after 97 μs
[16:27:07] Starting 'server-dev'...
[16:27:07] Starting 'server-watch-$deps$'...
[16:27:07] Starting '.init-bundle.valid.log'...
[16:27:07] Finished '.init-bundle.valid.log' after 470 μs
[16:27:07] Finished 'server-watch-$deps$' after 1.82 ms
[16:27:07] Starting 'server-watch'...
[16:27:07] Starting 'generate-service-worker'...
[16:27:07] Finished 'generate-service-worker' after 311 μs
[nodemon] 1.10.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: .etmp/bundle.valid.log /Users/kbsmith/work/scratch/example-electrode-app/server/**/* /Users/kbsmith/work/scratch/example-electrode-app/config/**/*
Entry point configuration is not found, using default entry point...
  0% compile http://localhost:2992/webpack-dev-server/
webpack result is served from http://localhost:2992/js/
content is served from /Users/kbsmith/work/scratch/example-electrode-app
 10% 0/1 build modules{ [Error: Cannot find module 'babel-preset-es2015'] code: 'MODULE_NOT_FOUND' }
webpack bundle is now VALID but has ERRORS
webpack report is served from http://localhost:2992/reporter
^C
```
Looks like we're missing `babel-preset-2015`. [Here's the reporter log](https://gist.github.com/knksmith57/fd88e7142551c3464d3fd338792e589f).

We'll init git to track changes:
```
❯ git init && git add . && git commit -m 'initial commit'
```

OK, so we install babel-preset-es2015:
```
❯ npm i --save babel-preset-es2015
npm WARN unmet dependency /Users/kbsmith/work/scratch/example-electrode-app/node_modules/electrode-server/node_modules/hapi/node_modules/subtext/node_modules/pez requires boom@'3.x.x' but will load
npm WARN unmet dependency /Users/kbsmith/work/scratch/example-electrode-app/node_modules/electrode-server/node_modules/hapi/node_modules/boom,
npm WARN unmet dependency which is version 4.0.0
babel-preset-es2015@6.16.0 node_modules/babel-preset-es2015
├── babel-plugin-transform-es2015-duplicate-keys@6.8.0 (babel-types@6.16.0, babel-runtime@6.11.6)
├── babel-plugin-transform-es2015-sticky-regex@6.8.0 (babel-helper-regex@6.9.0, babel-types@6.16.0, babel-runtime@6.11.6)
├── babel-plugin-transform-es2015-modules-amd@6.8.0 (babel-template@6.16.0, babel-runtime@6.11.6)
├── babel-plugin-transform-es2015-spread@6.8.0 (babel-runtime@6.11.6)
├── babel-plugin-transform-es2015-template-literals@6.8.0 (babel-runtime@6.11.6)
├── babel-plugin-transform-es2015-destructuring@6.16.0 (babel-runtime@6.11.6)
├── babel-plugin-transform-es2015-modules-umd@6.12.0 (babel-template@6.16.0, babel-runtime@6.11.6)
├── babel-plugin-transform-es2015-block-scoped-functions@6.8.0 (babel-runtime@6.11.6)
├── babel-plugin-transform-es2015-literals@6.8.0 (babel-runtime@6.11.6)
├── babel-plugin-transform-es2015-modules-systemjs@6.14.0 (babel-helper-hoist-variables@6.8.0, babel-template@6.16.0, babel-runtime@6.11.6)
├── babel-plugin-transform-es2015-arrow-functions@6.8.0 (babel-runtime@6.11.6)
├── babel-plugin-transform-es2015-for-of@6.8.0 (babel-runtime@6.11.6)
├── babel-plugin-transform-es2015-typeof-symbol@6.8.0 (babel-runtime@6.11.6)
├── babel-plugin-transform-es2015-parameters@6.17.0 (babel-helper-get-function-arity@6.8.0, babel-helper-call-delegate@6.8.0, babel-template@6.16.0, babel-types@6.16.0, babel-traverse@6.16.0, babel-runtime@6.11.6)
├── babel-plugin-check-es2015-constants@6.8.0 (babel-runtime@6.11.6)
├── babel-plugin-transform-es2015-unicode-regex@6.11.0 (regexpu-core@2.0.0, babel-helper-regex@6.9.0, babel-runtime@6.11.6)
├── babel-plugin-transform-regenerator@6.16.1 (private@0.1.6, babel-types@6.16.0, babel-runtime@6.11.6)
├── babel-plugin-transform-es2015-computed-properties@6.8.0 (babel-template@6.16.0, babel-helper-define-map@6.9.0, babel-runtime@6.11.6)
├── babel-plugin-transform-es2015-object-super@6.8.0 (babel-helper-replace-supers@6.16.0, babel-runtime@6.11.6)
├── babel-plugin-transform-es2015-function-name@6.9.0 (babel-types@6.16.0, babel-helper-function-name@6.8.0, babel-runtime@6.11.6)
├── babel-plugin-transform-es2015-modules-commonjs@6.16.0 (babel-plugin-transform-strict-mode@6.11.3, babel-types@6.16.0, babel-template@6.16.0, babel-runtime@6.11.6)
├── babel-plugin-transform-es2015-shorthand-properties@6.8.0 (babel-types@6.16.0, babel-runtime@6.11.6)
├── babel-plugin-transform-es2015-block-scoping@6.15.0 (babel-template@6.16.0, babel-types@6.16.0, babel-traverse@6.16.0, babel-runtime@6.11.6)
└── babel-plugin-transform-es2015-classes@6.14.0 (babel-messages@6.8.0, babel-helper-define-map@6.9.0, babel-helper-replace-supers@6.16.0, babel-helper-optimise-call-expression@6.8.0, babel-helper-function-name@6.8.0, babel-template@6.16.0, babel-types@6.16.0, babel-traverse@6.16.0, babel-runtime@6.11.6)
```

And try again:
```
❯ gulp dev
[16:31:34] Using gulpfile ~/work/scratch/example-electrode-app/gulpfile.js
[16:31:34] Starting 'dev'...
[16:31:34] Starting '.webpack-dev'...
[16:31:34] Finished '.webpack-dev' after 96 μs
[16:31:34] Starting 'server-dev'...
[16:31:34] Starting 'server-watch-$deps$'...
[16:31:34] Starting '.init-bundle.valid.log'...
[16:31:34] Finished '.init-bundle.valid.log' after 2.68 ms
[16:31:34] Finished 'server-watch-$deps$' after 3.96 ms
[16:31:34] Starting 'server-watch'...
[16:31:34] Starting 'generate-service-worker'...
[16:31:34] Finished 'generate-service-worker' after 252 μs
[nodemon] 1.10.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: .etmp/bundle.valid.log /Users/kbsmith/work/scratch/example-electrode-app/server/**/* /Users/kbsmith/work/scratch/example-electrode-app/config/**/*
Entry point configuration is not found, using default entry point...
isomorphic-loader webpack plugin: removed existing config file
  0% compile http://localhost:2992/webpack-dev-server/
webpack result is served from http://localhost:2992/js/
content is served from /Users/kbsmith/work/scratch/example-electrode-app
webpack bundle is now VALID but has ERRORS
webpack report is served from http://localhost:2992/reporter
```
Made it past the babel error, but the build still failed. [Here's the reporter log](https://gist.github.com/knksmith57/a27979560e25d65df530030aeff5c1e7).

Looks like we're missing `react-router`, `react-resolver`, and whatever is causing those `babel-runtime/helpers/*` issues. Let's do the 2 react dependencies first:
```
❯ npm i --save react-router react-resolver
npm WARN peerDependencies The peer dependency react@^0.14.6 || ^15.0.0-0 included from react-resolver will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency react-dom@^0.14.6 || ^15.0.0-0 included from react-resolver will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency react@^0.14.0 || ^15.0.0 included from react-router will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN unmet dependency /Users/kbsmith/work/scratch/example-electrode-app/node_modules/electrode-server/node_modules/hapi/node_modules/subtext/node_modules/pez requires boom@'3.x.x' but will load
npm WARN unmet dependency /Users/kbsmith/work/scratch/example-electrode-app/node_modules/electrode-server/node_modules/hapi/node_modules/boom,
npm WARN unmet dependency which is version 4.0.0
react-router@2.8.1 node_modules/react-router
├── invariant@2.2.1
├── warning@3.0.0
├── hoist-non-react-statics@1.2.0
├── loose-envify@1.2.0 (js-tokens@1.0.3)
└── history@2.1.2 (warning@2.1.0, deep-equal@1.0.1, query-string@3.0.3)

react-dom@15.3.2 node_modules/react-dom

react@15.3.2 node_modules/react
├── object-assign@4.1.0
├── loose-envify@1.2.0 (js-tokens@1.0.3)
└── fbjs@0.8.5 (immutable@3.8.1, ua-parser-js@0.7.10, promise@7.1.1, isomorphic-fetch@2.2.1, core-js@1.2.7)

react-resolver@3.0.3 node_modules/react-resolver
```

Annnddd now the build:
```
❯ gulp dev
[16:35:32] Using gulpfile ~/work/scratch/example-electrode-app/gulpfile.js
[16:35:32] Starting 'dev'...
[16:35:32] Starting '.webpack-dev'...
[16:35:32] Finished '.webpack-dev' after 106 μs
[16:35:32] Starting 'server-dev'...
[16:35:32] Starting 'server-watch-$deps$'...
[16:35:32] Starting '.init-bundle.valid.log'...
[16:35:32] Finished '.init-bundle.valid.log' after 1.05 ms
[16:35:32] Finished 'server-watch-$deps$' after 2.38 ms
[16:35:32] Starting 'server-watch'...
[16:35:32] Starting 'generate-service-worker'...
[16:35:32] Finished 'generate-service-worker' after 275 μs
[nodemon] 1.10.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: .etmp/bundle.valid.log /Users/kbsmith/work/scratch/example-electrode-app/server/**/* /Users/kbsmith/work/scratch/example-electrode-app/config/**/*
Entry point configuration is not found, using default entry point...
isomorphic-loader webpack plugin: removed existing config file
  0% compile http://localhost:2992/webpack-dev-server/
webpack result is served from http://localhost:2992/js/
content is served from /Users/kbsmith/work/scratch/example-electrode-app
webpack bundle is now VALID but has ERRORS
webpack report is served from http://localhost:2992/reporter
```
Build still failed. [Here's the reporter log](https://gist.github.com/knksmith57/3354a5b7ae88d8f738f5022a0fd6d77a).

Almost there! But we're still getting those  `babel-runtime/helpers/*` errors. Some quick googling led me to [this github issue](https://github.com/babel/babel/issues/1872#issuecomment-116845919). So we try installing `babel-runtime`:
```
❯ npm i --save babel-runtime
npm WARN unmet dependency /Users/kbsmith/work/scratch/example-electrode-app/node_modules/electrode-server/node_modules/hapi/node_modules/subtext/node_modules/pez requires boom@'3.x.x' but will load
npm WARN unmet dependency /Users/kbsmith/work/scratch/example-electrode-app/node_modules/electrode-server/node_modules/hapi/node_modules/boom,
npm WARN unmet dependency which is version 4.0.0
babel-runtime@6.11.6 node_modules/babel-runtime
├── regenerator-runtime@0.9.5
└── core-js@2.4.1
```

anndd the build again:
```
❯ gulp dev
[16:38:48] Using gulpfile ~/work/scratch/example-electrode-app/gulpfile.js
[16:38:48] Starting 'dev'...
[16:38:48] Starting '.webpack-dev'...
[16:38:48] Finished '.webpack-dev' after 91 μs
[16:38:48] Starting 'server-dev'...
[16:38:48] Starting 'server-watch-$deps$'...
[16:38:48] Starting '.init-bundle.valid.log'...
[16:38:48] Finished '.init-bundle.valid.log' after 2.1 ms
[16:38:48] Finished 'server-watch-$deps$' after 3.52 ms
[16:38:48] Starting 'server-watch'...
[16:38:48] Starting 'generate-service-worker'...
[16:38:48] Finished 'generate-service-worker' after 350 μs
[nodemon] 1.10.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: .etmp/bundle.valid.log /Users/kbsmith/work/scratch/example-electrode-app/server/**/* /Users/kbsmith/work/scratch/example-electrode-app/config/**/*
Entry point configuration is not found, using default entry point...
isomorphic-loader webpack plugin: removed existing config file
  0% compile http://localhost:2992/webpack-dev-server/
webpack result is served from http://localhost:2992/js/
content is served from /Users/kbsmith/work/scratch/example-electrode-app
webpack bundle is now VALID
webpack report is served from http://localhost:2992/reporter
[nodemon] restarting due to changes...
[nodemon] starting `node server/index.js`
```
Woot! Build passed! [Here's the reporter log](https://gist.github.com/knksmith57/1981d1d95130096c6d26a4fd83b09562).

Unfortunately, I then get this error in the console:
```
    ESERVERSTART

    This error is thrown by the electrode-server module

    There was an error starting the Hapi.js server
    Please check the output of the stack trace below and correct the error shown

    If you have followed this resolution step and you are still seeing an
    error, please file an issue on the electrode-server repository

    git+https://github.com/electrode-io/electrode-server.git


Unhandled rejection Error: Failed loading module inert: Cannot find module 'inert'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at tryCatcher (/Users/kbsmith/work/scratch/example-electrode-app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/kbsmith/work/scratch/example-electrode-app/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/kbsmith/work/scratch/example-electrode-app/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromiseCtx (/Users/kbsmith/work/scratch/example-electrode-app/node_modules/bluebird/js/release/promise.js:604:10)
    at Async._drainQueue (/Users/kbsmith/work/scratch/example-electrode-app/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/Users/kbsmith/work/scratch/example-electrode-app/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/kbsmith/work/scratch/example-electrode-app/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

A quick grep of the codebase reveals that `inert` is enabled as a plugin:
```
❯ ag inert
config/default.json
3:    "inert": {

config/production.js
2:// This file is here to allow enabling the plugins inert and electrodeStaticPaths, overriding the
16:    "inert": {
```

Looks like [it's used for static file serving](https://www.npmjs.com/package/inert). Let's install that...
```
❯ npm i --save inert
npm WARN unmet dependency /Users/kbsmith/work/scratch/example-electrode-app/node_modules/electrode-server/node_modules/hapi/node_modules/subtext/node_modules/pez requires boom@'3.x.x' but will load
npm WARN unmet dependency /Users/kbsmith/work/scratch/example-electrode-app/node_modules/electrode-server/node_modules/hapi/node_modules/boom,
npm WARN unmet dependency which is version 4.0.0
inert@4.0.2 node_modules/inert
├── boom@3.2.2
├── ammo@2.0.2
├── items@2.1.1
├── hoek@4.1.0
├── lru-cache@4.0.1 (pseudomap@1.0.2, yallist@2.0.0)
└── joi@9.1.0 (topo@2.0.2, isemail@2.2.1, moment@2.15.1)
```

annnddd one more time:
```
❯ gulp dev
[16:42:29] Using gulpfile ~/work/scratch/example-electrode-app/gulpfile.js
[16:42:29] Starting 'dev'...
[16:42:29] Starting '.webpack-dev'...
[16:42:29] Finished '.webpack-dev' after 94 μs
[16:42:29] Starting 'server-dev'...
[16:42:29] Starting 'server-watch-$deps$'...
[16:42:29] Starting '.init-bundle.valid.log'...
[16:42:29] Finished '.init-bundle.valid.log' after 905 μs
[16:42:29] Finished 'server-watch-$deps$' after 2.08 ms
[16:42:29] Starting 'server-watch'...
[16:42:29] Starting 'generate-service-worker'...
[16:42:29] Finished 'generate-service-worker' after 334 μs
[nodemon] 1.10.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: .etmp/bundle.valid.log /Users/kbsmith/work/scratch/example-electrode-app/server/**/* /Users/kbsmith/work/scratch/example-electrode-app/config/**/*
Entry point configuration is not found, using default entry point...
isomorphic-loader webpack plugin: removed existing config file
  0% compile http://localhost:2992/webpack-dev-server/
webpack result is served from http://localhost:2992/js/
content is served from /Users/kbsmith/work/scratch/example-electrode-app
webpack bundle is now VALID
webpack report is served from http://localhost:2992/reporter
[nodemon] restarting due to changes...
[nodemon] starting `node server/index.js`
staticPaths Plugin: static files path prefix "dist"

Hapi.js server running at http://kbsmith-mac:3000
```

Boom. Hapi is running and I can view the app in my browser:
![image](https://cloud.githubusercontent.com/assets/796851/19055255/ac7c5654-8988-11e6-8592-ef6ab2539329.png)

Here's my resulting diff:
```
❯ git diff
diff --git a/package.json b/package.json
index 8ff2b5b..6d12eed 100644
--- a/package.json
+++ b/package.json
@@ -25,13 +25,20 @@
     "coverage": "gulp check"
   },
   "dependencies": {
+    "babel-preset-es2015": "^6.16.0",
+    "babel-runtime": "^6.11.6",
     "bluebird": "^3.4.6",
     "electrode-archetype-react-app": "^1.0.0",
     "electrode-confippet": "^1.0.0",
     "electrode-router-resolver-engine": "^1.0.0",
     "electrode-server": "^1.0.0",
     "electrode-static-paths": "^1.0.0",
-    "lodash": "^4.10.1"
+    "inert": "^4.0.2",
+    "lodash": "^4.10.1",
+    "react": "^15.3.2",
+    "react-dom": "^15.3.2",
+    "react-resolver": "^3.0.3",
+    "react-router": "^2.8.1"
   },
   "devDependencies": {
     "electrode-archetype-react-app-dev": "^1.0.0",
```

And, for posterity, the `package.json` that got it all working: https://gist.github.com/knksmith57/8a29fef221a1ccb8e08f6d29b2107ce8


Let me know if you want me to PR the updated `package.json` or if you'd like to take it from here.

Thanks!

**Comment by AlexG92** [comment]
Hello @knksmith57 ,

Thank you so much for the compliments, we are honored that you took a look at the platform and are trying to play with Electrode.

Electrode requires NPM flattening which is provided in NPM 3 (which is bundled in with Node v6). I would guess that you are using NPM 2 and that's what is causing the dependency issue. In your raw log on line 45, you'll see the `✖ npm version`

The NPM 3 requirement is called out in our "[requirements](http://www.electrode.io/docs/requirements.html)" page, but we will add it to our "[Getting Started](http://www.electrode.io/docs/get_started.html)" as well - as I think people will easily miss this requirement.

The solution you found (adding the dependencies to your app's top level) will work, but it removes the benefit of having archetype manage your dependencies.

The use case for archetype managing your dependencies is for when you have lots of applications or components and you want to bump a lib across all of them, instead of bumping every single app top level dependency, you just modify the archetype.

**Comment by knksmith57** [comment]
Ah, thanks for pointing that out @AlexG92! I should have taken a deeper look before commenting.

Totally agreed that it'd be cool to put it into the requirements section. This will likely be a non-issue in a few weeks as the node 6 LTS will bring along npm 3 by default.

Thanks for the quick response!

**Comment by AlexG92** [comment]
Thanks for taking the time to post an issue and the raw logs. Let us know if you have any other troubles :).
