### ISSUE TITLE
Reporter page is unavailable

### ISSUE THREAD

**Issue by VictorVolovik** [electrode-io/generator-electrode#56]
After running 
```
$ sudo npm install -g yo gulp generator-electrode
$ mkdir my-electrode-app
$ cd my-electrode-app
$ yo electrode
$ gulp dev
```

I was unable to access webpack reporter on url http://localhost:2992/reporter.

Chrome  54.0.2840.98 (64-bit)
Node.js  6.7.0
npm 3.10.3

Stack trace:
```
bundle.ce036e7….js:19 Uncaught Error: Cannot find module "electrode-electrify-react-component"
    at http://localhost:2992/node_modules/electrode-webpack-reporter/dist/js/bundle.ce036e7bc2fd87582627.js:19:22081
    at Object.<anonymous> (http://localhost:2992/node_modules/electrode-webpack-reporter/dist/js/bundle.ce036e7bc2fd87582627.js:19:22185)
    at t (http://localhost:2992/node_modules/electrode-webpack-reporter/dist/js/bundle.ce036e7bc2fd87582627.js:1:107)
    at Object.<anonymous> (http://localhost:2992/node_modules/electrode-webpack-reporter/dist/js/bundle.ce036e7bc2fd87582627.js:1:370)
    at t (http://localhost:2992/node_modules/electrode-webpack-reporter/dist/js/bundle.ce036e7bc2fd87582627.js:1:107)
    at http://localhost:2992/node_modules/electrode-webpack-reporter/dist/js/bundle.ce036e7bc2fd87582627.js:1:194
    at http://localhost:2992/node_modules/electrode-webpack-reporter/dist/js/bundle.ce036e7bc2fd87582627.js:1:199
```

I've tried
`npm i -S electrode-electrify-react-component`
then
`npm i -S react-tap-event-plugin`
but it didn't help.

**Comment by ananavati** [comment]
@VictorVolovik 

sorry for the inconvenience, fix for this bug in pr #58
