### ISSUE TITLE
Windows - fails to start

### ISSUE THREAD

**Issue by sonicviz** [electrode-io/generator-electrode#62]
Hi,
Looks like a great project and thought I'd test it as an alternative to Meteor.

I'm running on Windows 10, but can't get either the demos or generated app to run.
I get the following error. Checked the FAQ and have Node 4.5 and npm 4.2.0 etc
Any clues? ty!

=====================console log from steps listed in http://www.electrode.io/docs/get_started.html
=========================================
...*snip*
G:\Electrode Projects\app1>gulp dev
[17:11:17] Using gulpfile G:\Electrode Projects\app1\gulpfile.js
[17:11:17] Starting 'dev'...
[17:11:17] Starting '.webpack-dev'...
[17:11:17] Finished '.webpack-dev' after 117 μs
[17:11:17] Starting 'wds.dev'...
[17:11:17] Starting 'server-watch-$deps$'...
[17:11:17] Starting '.init-bundle.valid.log'...
[17:11:17] Finished '.init-bundle.valid.log' after 4.25 ms
[17:11:17] Finished 'server-watch-$deps$' after 6.97 ms
[17:11:17] Starting 'server-watch'...
[17:11:17] Starting 'generate-service-worker'...
[17:11:17] Finished 'generate-service-worker' after 537 μs
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: .etmp\bundle.valid.log G:\Electrode Projects\app1\src\server/**/* G:\Electrode Projects\app1\config/**/*
module.js:327
    throw err;
    ^

Error: Cannot find module 'G:\Electrode'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at module.exports (G:\Electrode Projects\app1\node_modules\webpack\bin\convert-argv.js:80:13)
    at Object.<anonymous> (G:\Electrode Projects\app1\node_modules\webpack-dev-server\bin\webpack-dev-server.js:68:48)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
[17:11:17] 'wds.dev' errored after 882 ms
[17:11:17] Error: command exit code 1
    at error (G:\Electrode Projects\app1\node_modules\electrode-gulp-helper\lib\exec.js:6:15)
    at G:\Electrode Projects\app1\node_modules\electrode-gulp-helper\lib\exec.js:39:29
    at G:\Electrode Projects\app1\node_modules\shelljs\src\exec.js:204:9
    at ChildProcess.exithandler (child_process.js:220:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:829:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
[17:11:17] 'dev' errored after 891 ms
[17:11:17] Error in plugin 'run-sequence(wds.dev)'
Message:
    command exit code 1

**Comment by sonicviz** [comment]
Any clues?

**Comment by jchip** [comment]
Please don't name directory or files with space `" "` in them.

**Comment by sonicviz** [comment]
tyvm!
